version: "3"
services:
    database:
        image: 'mongo'
        container_name: 'mongo-container'
        restart: always
        env_file: 
            - db/db.env
        volumes:
            - ./db/init.js:/docker-entrypoint-initdb.d/init.js:ro
            - ./db/volume:/data/db/
        ports:
            - '27017:27017'
    web:
        container_name: 'web-app-container'
        depends_on:
            - 'database'
        restart: always
        env_file: 
            - db/db.env
        build: .
        ports:
            - "8081:8080"